/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.de.frauas.progex.flatprotecc.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import main.java.de.frauas.progex.flatprotecc.Connect2DB;

/**
 *
 * @author lucas
 */
public class OverviewScreen extends javax.swing.JFrame {

    private int userId;
    private DefaultTableModel tableModel;

    /**
     * Creates new form OverviewScreen
     */
    public OverviewScreen(int userId) {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        this.userId = userId;

        setLocationRelativeTo(null);

        tableModel = new DefaultTableModel();

        jTable.setModel(tableModel);
        jTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        String[] columnNames = {"ID", "Title", "Username", "E-Mail", "Comment"};
        tableModel.setColumnIdentifiers(columnNames);
        //jTable.getColumn("Description").setPreferredWidth(300);

        // Der TableRowSorter wird die Daten des Models sortieren
        TableRowSorter<TableModel> sorter = new TableRowSorter<>();
        // Der Sorter muss dem JTable bekannt sein
        jTable.setRowSorter(sorter);
        // ... und der Sorter muss wissen, welche Daten er sortieren muss
        sorter.setModel(tableModel);
        // damit Spalten nicht verschoben werden können
        jTable.getTableHeader().setReorderingAllowed(false);

        jTable.getColumnModel().getColumn(0).setMinWidth(0);
        jTable.getColumnModel().getColumn(0).setMaxWidth(0);

        refreshTable();

    }

    private void refreshTable() {
        tableModel.setRowCount(0);
        try {
            Connect2DB con2db = new Connect2DB();
            Connection conn = con2db.StartConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM entry WHERE acc_id = " + userId);

            jTable.setDefaultEditor(Object.class, null);

            while (rs.next()) {

                String id = rs.getString("id");
                String title = rs.getString("title");
                String username = rs.getString("username");
                String email = rs.getString("mail");
                String com = rs.getString("com");

                tableModel.addRow(new Object[]{id, title, username, email, com});
            }

        } catch (Exception e) {
            System.out.println("Fehler in GUI/MainMenu/EventReadFromDB!");
            System.out.println("Auszug aus Fehlermeldung: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFLATprotecc = new javax.swing.JLabel();
        jButtonAddEntry = new javax.swing.JButton();
        jButtonChangeEmail = new javax.swing.JButton();
        jButtonChangePassword = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FLATprotecc - Password Manager");
        setMinimumSize(new java.awt.Dimension(500, 500));

        jLabelFLATprotecc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFLATprotecc.setText("FLATprotecc");

        jButtonAddEntry.setText("Add Entry");
        jButtonAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEntryActionPerformed(evt);
            }
        });

        jButtonChangeEmail.setText("Change E-Mail");
        jButtonChangeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeEmailActionPerformed(evt);
            }
        });

        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelFLATprotecc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(jButtonChangeEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonChangePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFLATprotecc, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButtonChangeEmail)
                    .addComponent(jButtonChangePassword)
                    .addComponent(jButtonAddEntry))
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeEmailActionPerformed
        // TODO add your handling code here:
        JFrame frame = this;
        frame.setEnabled(false);
        ChangeEmail ce;
        ce = new ChangeEmail(userId);
        ce.setVisible(true);

        ce.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                frame.setEnabled(true);
                frame.toFront();
            }
        });
    }//GEN-LAST:event_jButtonChangeEmailActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        JFrame frame = this;
        frame.setEnabled(false);
        ChangePassword cp;
        cp = new ChangePassword(userId);
        cp.setVisible(true);

        cp.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                frame.setEnabled(true);
                frame.toFront();
            }
        });


    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jButtonAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEntryActionPerformed
        // TODO add your handling code here:
        JFrame frame = this;
        frame.setEnabled(false);
        AddEntry ae;
        ae = new AddEntry(userId);
        ae.setVisible(true);

        ae.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                frame.setEnabled(true);
                frame.toFront();
                refreshTable();
            }
        });
    }//GEN-LAST:event_jButtonAddEntryActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        System.out.println(row + "selected id=" + table.getValueAt(row, 0));

        JFrame frame = this;
        frame.setEnabled(false);
        ShowEntry se = new ShowEntry(userId, Integer.valueOf((String) table.getValueAt(row, 0)));
        se.setVisible(true);

        se.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                frame.setEnabled(true);
                frame.toFront();
                refreshTable();
            }
        });
        
    }//GEN-LAST:event_jTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddEntry;
    private javax.swing.JButton jButtonChangeEmail;
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JLabel jLabelFLATprotecc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
